[pytest]
addopts = --strict-markers --disable-warnings
python_paths =
    .
    ./custom_components
markers =
    homeassistant: mark a test as requiring the Home Assistant test environment

# Enable Home Assistant test environment
plugins =
    pytest_homeassistant_custom_component

# Set asyncio mode to auto
asyncio_mode = auto
testpaths =
    ./tests
